import type { CipAirportOption, CipVehicleOption } from '@/lib/types';

export const CIP_AIRPORTS: CipAirportOption[] = [
  {
    id: 'cip-ika',
    airportCode: 'IKA',
    airportNameFa: 'فرودگاه بین‌المللی امام خمینی (ره)',
    airportNameEn: 'Imam Khomeini International Airport (IKA)',
    cityFa: 'تهران',
    cityEn: 'Tehran',
    countryCode: 'IR',
    terminal: 'ساختمان اختصاصی CIP (ضلع غربی ترمینال ۱)',
    basePriceAdult: 9900000, // ۹,۹۰۰,۰۰۰ تومان
    basePriceGuest: 3300000, // ۳,۳۰۰,۰۰۰ تومان (مشایع یا مستقبل)
    petServicePrice: 3740000, // ۳,۷۴۰,۰۰۰ تومان
    wheelchairPrice: 2970000, // ۲,۹۷۰,۰۰۰ تومان (دستگاه بالابر LOM باند)
    suite6hPrice: 5200000,   // ۵,۲۰۰,۰۰۰ تومان (سوئیت اقامتی ۶ ساعته)
    suite10hPrice: 5860000,  // ۵,۸۶۰,۰۰۰ تومان (سوئیت اقامتی ۱۰ ساعته)
    suiteOvernightPrice: 8470000, // ۸,۴۷۰,۰۰۰ تومان (اقامت شبانه هتل فرودگاهی)
    descriptionFa: 'بزرگترین و مجهزترین پایانه تشریفات اختصاصی کشور در ۳ طبقه و به وسعت ۷۰۰۰ مترمربع؛ شامل گیت‌های اختصاصی گذرنامه، بازرسی و گمرک، ترانسفر پای پلکان با خودروهای تشریفاتی، بوفه سلف‌سرویس مجلل و تحویل بار اختصاصی.',
    descriptionEn: 'The most prestigious executive lounge in Iran spanning 7,000 sqm across 3 floors. Private passport control & customs, luxury tarmac transfer to aircraft steps, all-inclusive gourmet buffet, and dedicated luggage handling.',
    featuresFa: [
      'گیت اختصاصی پلیس گذرنامه و گمرک بدون معطلی و صف',
      'ترانسفر روی باند تا پای پلکان هواپیما با خودروهای تشریفاتی',
      'اخذ کارت پرواز، تخصیص صندلی و تحویل بار توسط کارشناس تشریفات',
      'پذیرایی نامحدود سلف‌سرویس انواع غذاهای گرم، سرد، فینگرفود، دسر و نوشیدنی',
      'اینترنت پرسرعت Wi-Fi، باجه بانکی، اتاق تعویض نوزاد و اتاق اختصاصی سیگار',
      'سوئیت‌های اقامتی لوکس جهت استراحت موقت ساعتی و شبانه',
      'پارکینگ اختصاصی مسقف و روباز تشریفات با امنیت کامل',
    ],
    featuresEn: [
      'Dedicated express passport control & customs with zero queues',
      'Private tarmac limousine escort directly to aircraft stairs',
      'Full check-in, seat assignment, and luggage handling by CIP agents',
      'Unlimited gourmet buffet featuring hot/cold entrees, desserts & refreshments',
      'High-speed Wi-Fi, private banking counter, smoking lounge & nursery',
      'On-site private day suites and direct airbridge to airport hotels',
      'Guarded dedicated parking facility with valet service',
    ],
    image: 'https://images.unsplash.com/photo-1541348263662-e0c8de4259ba?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1541348263662-e0c8de4259ba?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    ],
    rating: 4.9,
    reviewsCount: 1420,
    isFlagship: true,
  },
  {
    id: 'cip-mhd',
    airportCode: 'MHD',
    airportNameFa: 'فرودگاه بین‌المللی شهید هاشمی‌نژاد مشهد',
    airportNameEn: 'Mashhad Shahid Hasheminejad Airport (MHD)',
    cityFa: 'مشهد',
    cityEn: 'Mashhad',
    countryCode: 'IR',
    terminal: 'جایگاه اختصاصی تشریفات CIP ترمینال پروازهای خارجی',
    basePriceAdult: 6800000,
    basePriceGuest: 2500000,
    petServicePrice: 2800000,
    wheelchairPrice: 2100000,
    suite6hPrice: 3500000,
    suite10hPrice: 4200000,
    suiteOvernightPrice: 5900000,
    descriptionFa: 'سالن تشریفات اختصاصی فرودگاه بین‌المللی مشهد با ارائه خدمات VIP/CIP به زائران و مسافران پروازهای خارجی و داخلی همراه با پذیرایی سلف‌سرویس و ترانسفر باند.',
    descriptionEn: 'Dedicated executive CIP terminal at Mashhad International Airport offering premium lounge services, catering, and tarmac transfers for domestic and international travelers.',
    featuresFa: [
      'گیت‌های مستقل امنیتی و گذرنامه',
      'ترانسفر اختصاصی تا پای پرواز',
      'بوفه آزاد و استراحتگاه مجهز',
      'انجام کلیه مراحل بار و پرواز توسط پرسنل',
    ],
    featuresEn: [
      'Independent security and passport clearance',
      'Dedicated tarmac apron transfer',
      'Open buffet and relaxation lounge',
      'Complete baggage and boarding handling',
    ],
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80',
    rating: 4.8,
    reviewsCount: 860,
  },
  {
    id: 'cip-syz',
    airportCode: 'SYZ',
    airportNameFa: 'فرودگاه بین‌المللی شهید دستغیب شیراز',
    airportNameEn: 'Shiraz Shahid Dastghaib Airport (SYZ)',
    cityFa: 'شیراز',
    cityEn: 'Shiraz',
    countryCode: 'IR',
    terminal: 'ترمینال تشریفات اختصاصی',
    basePriceAdult: 6200000,
    basePriceGuest: 2300000,
    petServicePrice: 2500000,
    wheelchairPrice: 1900000,
    suite6hPrice: 3200000,
    suite10hPrice: 3900000,
    suiteOvernightPrice: 5400000,
    descriptionFa: 'جایگاه تشریفات مجلل فرودگاه شیراز با معماری سنتی اصیل و مدرن، گیت‌های مستقل و پذیرایی ویژه پذیرای مسافران خارجی و داخلی.',
    descriptionEn: 'Elegant CIP lounge in Shiraz featuring traditional Persian hospitality, express clearance gates, and VIP apron transfer.',
    featuresFa: [
      'عبور سریع بدون صف از بازرسی و گذرنامه',
      'پذیرایی سنتی شیرازی و فرنگی سلف‌سرویس',
      'انتقال اختصاصی با لیموزین به پای هواپیما',
    ],
    featuresEn: [
      'Fast-track passport and security',
      'Traditional Persian and international buffet',
      'Luxury tarmac transfer',
    ],
    image: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?auto=format&fit=crop&w=1200&q=80',
    rating: 4.8,
    reviewsCount: 640,
  },
  {
    id: 'cip-kih',
    airportCode: 'KIH',
    airportNameFa: 'فرودگاه بین‌المللی کیش',
    airportNameEn: 'Kish International Airport (KIH)',
    cityFa: 'جزیره کیش',
    cityEn: 'Kish Island',
    countryCode: 'IR',
    terminal: 'ترمینال جدید و سالن اختصاصی تشریفات CIP',
    basePriceAdult: 6500000,
    basePriceGuest: 2400000,
    petServicePrice: 2600000,
    wheelchairPrice: 1900000,
    suite6hPrice: 3400000,
    suite10hPrice: 4100000,
    suiteOvernightPrice: 5600000,
    descriptionFa: 'خدمات تشریفات مدرن در ترمینال جدید فرودگاه کیش، سالن آرام با امکانات استراحت، پذیرایی کامل و تحویل چمدان بدون معطلی.',
    descriptionEn: 'Modern executive lounge at Kish Island Airport offering seamless VIP boarding, baggage delivery, and luxury refreshments.',
    featuresFa: [
      'پذیرش ویژه و تحویل بار بدون معطلی',
      'ترانسفر باند با خودروهای شاسی‌بلند تشریفات',
      'کافی‌شاپ و بوفه پذیرایی ویژه جزیره',
    ],
    featuresEn: [
      'Express luggage check-in and claim',
      'Luxury SUV tarmac transfer',
      'Premium island refreshments and coffee',
    ],
    image: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1200&q=80',
    rating: 4.9,
    reviewsCount: 920,
  },
  {
    id: 'cip-tbz',
    airportCode: 'TBZ',
    airportNameFa: 'فرودگاه بین‌المللی شهید مدنی تبریز',
    airportNameEn: 'Tabriz Shahid Madani Airport (TBZ)',
    cityFa: 'تبریز',
    cityEn: 'Tabriz',
    countryCode: 'IR',
    terminal: 'سالن تشریفات اختصاصی VIP/CIP',
    basePriceAdult: 5800000,
    basePriceGuest: 2100000,
    petServicePrice: 2400000,
    wheelchairPrice: 1800000,
    suite6hPrice: 2900000,
    suite10hPrice: 3600000,
    suiteOvernightPrice: 4900000,
    descriptionFa: 'جایگاه تشریفات CIP تبریز با پذیرایی از پروازهای بین‌المللی باکو، استانبول و پروازهای داخلی در محیطی آرام و مجلل.',
    descriptionEn: 'Tabriz International Airport executive CIP salon catering to international flights to Istanbul, Baku and domestic connections.',
    featuresFa: [
      'گیت‌های گذرنامه و گمرک اختصاصی',
      'بوفه پذیرایی و سوغات اصیل تبریز',
      'ترانسفر اختصاصی پای پلکان پرواز',
    ],
    featuresEn: [
      'Dedicated customs & passport gates',
      'Traditional Tabrizi pastries and buffet',
      'Private flight steps escort',
    ],
    image: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=1200&q=80',
    rating: 4.7,
    reviewsCount: 430,
  },
  {
    id: 'cip-dxb',
    airportCode: 'DXB',
    airportNameFa: 'فرودگاه بین‌المللی دبی (Marhaba & Ahlan VIP)',
    airportNameEn: 'Dubai International Airport (DXB Marhaba & Ahlan)',
    cityFa: 'دبی',
    cityEn: 'Dubai',
    countryCode: 'AE',
    terminal: 'ترمینال ۱، ۲ و ۳ (سالن‌های لانژ مرحبا و اهلا)',
    basePriceAdult: 21500000,
    basePriceGuest: 7500000,
    petServicePrice: 8500000,
    wheelchairPrice: 4500000,
    suite6hPrice: 12000000,
    suite10hPrice: 16000000,
    suiteOvernightPrice: 24000000,
    descriptionFa: 'خدمات تشریفات بین‌المللی مرحبا و اهلا در فرودگاه دبی شامل اسکورت پای پرواز، گذرنامه سریع Fast Track و دسترسی به مجلل‌ترین لانژهای دنیا.',
    descriptionEn: 'World-class Marhaba & Ahlan VIP meet & greet service across all Dubai terminals with fast-track immigration and premier lounge access.',
    featuresFa: [
      'استقبال اختصاصی پای گیت پرواز با نام مسافر',
      'تردد از مسیر سریع Fast Track گذرنامه و بازرسی',
      'لانژ بین‌المللی با غذاهای گرم چندملیتی و نوشیدنی‌های نفیس',
      'باگی اختصاصی برقی برای تردد سریع در ترمینال',
    ],
    featuresEn: [
      'Dedicated airbridge meet and greet with nameboard',
      'Fast-track immigration and security channels',
      'Five-star international dining and luxury beverages',
      'Dedicated buggy car transfer through terminal',
    ],
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80',
    rating: 4.9,
    reviewsCount: 3100,
  },
];

export const CIP_VEHICLES: CipVehicleOption[] = [
  {
    id: 'v_sedan_eco',
    nameFa: 'سواری اقتصادی (سمند / پارس / تندر ۹۰)',
    nameEn: 'Economy Sedan (Samand / Peugeot Pars / L90)',
    category: 'sedan_economy',
    capacity: 3,
    luggageCapacity: 3,
    priceTehran: 1800000, // ۱,۸۰۰,۰۰۰ تومان
    priceSuburbs: 2400000, // ۲,۴۰۰,۰۰۰ تومان (کرج / لواسان / پردیس)
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'v_sedan_mid',
    nameFa: 'سدان باکیفیت (تویوتا کمری / رنو سفران / کیا سراتو)',
    nameEn: 'Premium Sedan (Toyota Camry / Renault Safrane / Cerato)',
    category: 'sedan_luxury',
    capacity: 3,
    luggageCapacity: 3,
    priceTehran: 2190000, // ۲,۱۹۰,۰۰۰ تومان
    priceSuburbs: 2490000, // ۲,۴۹۰,۰۰۰ تومان
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'v_suv_electric',
    nameFa: 'شاسی‌بلند مدرن برقی آیون (Aion Electric SUV)',
    nameEn: 'Modern Electric SUV (GAC Aion)',
    category: 'suv',
    capacity: 4,
    luggageCapacity: 4,
    priceTehran: 2390000, // ۲,۳۹۰,۰۰۰ تومان
    priceSuburbs: 3290000, // ۳,۲۹۰,۰۰۰ تومان
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'v_suv_rav4',
    nameFa: 'شاسی‌بلند تویوتا Rav4 / هیوندای سانتافه New',
    nameEn: 'SUV (Toyota RAV4 / Hyundai Santa Fe)',
    category: 'suv_luxury',
    capacity: 4,
    luggageCapacity: 4,
    priceTehran: 2490000, // ۲,۴۹۰,۰۰۰ تومان
    priceSuburbs: 3390000, // ۳,۳۹۰,۰۰۰ تومان
    image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'v_van_airport',
    nameFa: 'ون فرودگاهی استاندارد (ظرفیت بالا)',
    nameEn: 'Standard Airport Van (High Capacity)',
    category: 'van',
    capacity: 7,
    luggageCapacity: 10,
    priceTehran: 3200000, // ۳,۲۰۰,۰۰۰ تومان
    priceSuburbs: 4100000, // ۴,۱۰۰,۰۰۰ تومان
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'v_van_hiace',
    nameFa: 'ون تشریفاتی تویوتا هایس (Toyota HiAce VIP)',
    nameEn: 'Executive Van (Toyota HiAce VIP)',
    category: 'van',
    capacity: 10,
    luggageCapacity: 12,
    priceTehran: 5500000, // ۵,۵۰۰,۰۰۰ تومان
    priceSuburbs: 6500000, // ۶,۵۰۰,۰۰۰ تومان
    image: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'v_vip_s500',
    nameFa: 'تشریفات فوق لوکس مرسدس بنز S500 / تویوتا لندکروزر V6',
    nameEn: 'Ultra VIP (Mercedes S500 / Land Cruiser V6)',
    category: 'vip',
    capacity: 3,
    luggageCapacity: 4,
    priceTehran: 9200000, // ۹,۲۰۰,۰۰۰ تومان
    priceSuburbs: 10500000, // ۱۰,۵۰۰,۰۰۰ تومان
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80',
  },
];
