import type { Tour } from '@/lib/types';
import { daysFromNow } from '@/lib/utils';

export const DETAILED_TOURS: Tour[] = [
  {
    id: 't1',
    title: 'تور فرهنگی اصفهان - نصف جهان',
    titleEn: 'Isfahan Cultural Heritage Tour',
    city: 'اصفهان',
    cityEn: 'Isfahan',
    country: 'ایران',
    countryEn: 'Iran',
    durationDays: 3,
    durationNights: 2,
    price: 85000000,
    childPrice: 58000000,
    rating: 4.8,
    reviewsCount: 142,
    imageQuery: 'isfahan-mosque',
    category: 'cultural',
    heroImage: '/images/isfahan/sheikh-lotfollah-exterior.jpg',
    gallery: [
      '/images/isfahan/sheikh-lotfollah-exterior.jpg',
      '/images/isfahan/sheikh-lotfollah.jpg',
      '/images/isfahan/ali-qapu.jpg',
      '/images/isfahan/khaju-bridge.jpg',
      '/images/isfahan/khaju-pavilion.jpg',
      '/images/isfahan/khaju-day.jpg',
      '/images/isfahan/chehel-sotoun.jpg',
      '/images/isfahan/menar-jonban.jpg',
      '/images/isfahan/shah-mosque.jpg',
      '/images/isfahan/jameh-mosque.jpg',
      '/images/isfahan/bazaar-handicrafts.jpg',
      '/images/isfahan/isfahan-emblem.jpg',
    ],
    summary: 'سفری رؤیایی به پایتخت هنر و معماری صفوی، اقامت در مجلل‌ترین کاروانسرای ۵ ستاره خاورمیانه و تجربه طعم‌ها و سنت‌های اصیل نصف جهان.',
    summaryEn: 'A magical journey to the capital of Safavid art and architecture, staying at the luxury 5-star Abbasi Hotel and discovering the treasures of Isfahan.',
    description: 'اصفهان با نام پرآوازه «نصف جهان»، گنجینه‌ای بی‌بدیل از هنر، معماری و تاریخ ایران کهن است. در این تور اختصاصی ۳ روزه، شما با همراهی راهنمای مجرب و برگزیده میراث فرهنگی، شکوه میدان نقش جهان، شاهکار کاشی‌کاری‌های مسجد شیخ لطف‌الله، نقاشی‌های دیواری کاخ چهلستون و کلیسای وانک جلفا را از نزدیک لمس خواهید کرد. تمامی ترانسفرهای فرودگاهی و درون‌شهری با خودروهای تشریفاتی VIP انجام شده و اقامت شما در هتل ۵ ستاره مجلل عباسی با چشم‌انداز باغ ایرانی تضمین شده است.',
    descriptionEn: 'Known as "Half the World", Isfahan is an unparalleled treasure of Iranian culture, art, and architectural masterpieces. On this exclusive 3-day curated tour, accompanied by an accredited heritage guide, you will marvel at Naqsh-e Jahan Square, Sheikh Lotfollah Mosque, Chehel Sotoun palace frescoes, and the Armenian Vank Cathedral. Complete with luxury VIP transfers and stay at the historic 5-star Abbasi Hotel.',
    highlights: [
      'بازدید کامل از میدان جهانی نقش جهان (میراث یونسکو)',
      'کاخ عالی قاپو و اتاق موسیقی بی‌نظیر آن',
      'مسجد شیخ لطف‌الله با گنبد فیروزه‌ای منحصربه‌فرد',
      'عصرانه سنتی چای و باقلوا در چایخانه تاریخی هتل عباسی',
      'محله‌گردی در جلفای نو و بازدید از کلیسای تاریخی وانک',
      'گشت شبانه بر روی پل خواجو و سی‌وسه‌پل با نوای آواز سنتی',
      'کارگاه قلم‌زنی و خرید گز اصیل اصفهان',
    ],
    highlightsEn: [
      'Full exploration of UNESCO-listed Naqsh-e Jahan Square',
      'Ali Qapu Palace and its breathtaking acoustic Music Room',
      'The sublime domed architecture of Sheikh Lotfollah Mosque',
      'Traditional afternoon tea at the courtyard garden of historic Abbasi Hotel',
      'Walking tour in New Julfa Armenian quarter and Vank Cathedral',
      'Evening illuminated stroll along Khaju and Si-o-se-pol bridge pavilions',
      'Artisan handicraft workshops and authentic Gaz tasting',
    ],
    includes: [
      'بلیط پرواز رفت و برگشت با هواپیمایی ماهان',
      '۲ شب اقامت در هتل ۵ ستاره عباسی (با صبحانه بوفه کامل)',
      'ترانسفر اختصاصی فرودگاهی و گشت‌های شهری VIP',
      'راهنمای رسمی و مجرب میراث فرهنگی و گردشگری',
      'ورودیه تمامی اماکن تاریخی و موزه‌های ذکر شده در برنامه',
      'بیمه مسافرتی معتبر سامان تا سقف ۱۰,۰۰۰ یورو',
      'پذیرایی میان‌وعده و آب معدنی در طول گشت‌ها',
    ],
    excludes: [
      'وعده‌های ناهار و شام (به جز موارد قید شده)',
      'هزینه خریدهای شخصی و سوغاتی',
      'انعام راهنما و راننده',
    ],
    hotelName: 'هتل ۵ ستاره عباسی اصفهان',
    hotelStars: 5,
    transportType: 'پرواز رفت و برگشت ماهان + ون تشریفات VIP',
    transportTypeEn: 'Return flights (Mahan Air) + VIP Mercedes Van',
    groupSize: 'حداکثر ۱۲ نفر (تور نیمه‌خصوصی)',
    groupSizeEn: 'Max 12 people (semi-private)',
    guideLanguages: ['فارسی', 'English'],
    cancellationPolicy: {
      freeUntilDays: 7,
      description: 'کنسلی تا ۷ روز پیش از حرکت بدون جریمه و با بازگشت ۱۰۰٪ وجه صورت می‌پذیرد. از ۷ تا ۳ روز قبل کسر ۳۰٪ و کمتر از ۷۲ ساعت قبل بدون استرداد خواهد بود.',
      descriptionEn: 'Free cancellation up to 7 days before departure with 100% refund. 30% penalty between 7 and 3 days before departure. Non-refundable within 72 hours.',
    },
    departureDates: [
      {
        id: 'd1-t1',
        startDate: daysFromNow(5),
        endDate: daysFromNow(8),
        price: 85000000,
        childPrice: 58000000,
        availableSeats: 6,
        guaranteed: true,
      },
      {
        id: 'd2-t1',
        startDate: daysFromNow(12),
        endDate: daysFromNow(15),
        price: 85000000,
        childPrice: 58000000,
        availableSeats: 9,
        guaranteed: true,
      },
      {
        id: 'd3-t1',
        startDate: daysFromNow(19),
        endDate: daysFromNow(22),
        price: 88000000,
        childPrice: 60000000,
        availableSeats: 12,
        guaranteed: true,
      },
      {
        id: 'd4-t1',
        startDate: daysFromNow(26),
        endDate: daysFromNow(29),
        price: 85000000,
        childPrice: 58000000,
        availableSeats: 8,
        guaranteed: true,
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'ورود به نصف جهان و نغمه‌های پل‌های زاینده‌رود',
        titleEn: 'Arrival in Isfahan & Bridges of Zayandeh Rood',
        description: 'استقبال فرودگاهی و ترانسفر به هتل تاریخی عباسی. پس از تحویل اتاق و استراحت، عصرگاه راهی سی‌وسه‌پل و پل خواجو می‌شویم تا غروب دل‌انگیز و نوای آواز سنتی را در دهانه‌های تاریخی پل تجربه کنیم.',
        descriptionEn: 'Airport welcome and private transfer to Abbasi Hotel. After check-in and leisure time, we visit Si-o-se-pol and Khaju Bridge at sunset, admiring the stone acoustics and serene atmosphere.',
        activities: ['استقبال فرودگاهی و پذیرش هتل', 'گشت عصرگاهی در حاشیه زاینده‌رود', 'پیاده‌روی و عکاسی روی پل خواجو و سی‌وسه‌پل', 'شام خوشامدگویی بریانی اصیل اصفهان'],
        activitiesEn: ['Airport pickup & check-in', 'Evening river promenade', 'Sunset photography at historic bridges', 'Welcome dinner featuring authentic Briyani'],
        meals: { breakfast: false, lunch: false, dinner: true },
        accommodation: 'هتل ۵ ستاره عباسی (اتاق پردیس رو به باغ)',
        accommodationEn: '5-star Abbasi Hotel (Pardis Garden Room)',
        image: '/images/isfahan/khaju-bridge.jpg',
      },
      {
        day: 2,
        title: 'شکوه میدان نقش جهان و رازهای دوران صفوی',
        titleEn: 'The Majesty of Naqsh-e Jahan Square',
        description: 'روز کامل اختصاص دارد به یکی از بزرگ‌ترین میدان‌های تاریخی جهان؛ بازدید از مسجد امام با طنین شگفت‌انگیز صدا در زیر گنبد، مسجد شیخ لطف‌الله با مقرنس‌های بی‌مانند، عمارت ۶ طبقه عالی قاپو و خرید از راسته‌های بازار قیصریه.',
        descriptionEn: 'Full day immersed in UNESCO masterpiece Naqsh-e Jahan. Explore Shah Mosque with its acoustic dome, the mesmerizing floral tiles of Sheikh Lotfollah, Ali Qapu Palace, and the lively handicraft bazaar.',
        activities: ['بازدید از مسجد امام و عمارت عالی‌قاپو', 'تماشای شاهکار معماری مسجد شیخ لطف‌الله', 'ناهار در سفره‌خانه سنتی باستان', 'کارگاه زنده قلم‌زنی و میناکاری'],
        activitiesEn: ['Visit Imam Mosque & Ali Qapu Palace', 'Tour Sheikh Lotfollah tilework marvel', 'Traditional Persian lunch', 'Live copper engraving and Minakari workshop'],
        meals: { breakfast: true, lunch: true, dinner: false },
        accommodation: 'هتل ۵ ستاره عباسی',
        accommodationEn: '5-star Abbasi Hotel',
        image: '/images/isfahan/ali-qapu.jpg',
      },
      {
        day: 3,
        title: 'محله ارمنی‌های جلفا، کاخ چهلستون و بدرقه',
        titleEn: 'Armenian Julfa, Chehel Sotoun & Farewell',
        description: 'صبح به کلیسای تاریخی وانک و موزه جلفا سر می‌زنیم و طعم قهوه اصیل ارمنی را می‌چشیم. سپس از باغ و کاخ چهلستون با نقاشی‌های دیواری باشکوه دیدن کرده و پس از خرید گز درجه یک، راهی فرودگاه می‌شویم.',
        descriptionEn: 'Morning walking tour of the picturesque New Julfa quarter, visiting Vank Cathedral and Museum. Next, admire Chehel Sotoun palace garden. Conclude with souvenir shopping and airport transfer.',
        activities: ['بازدید از کلیسای وانک و موزه مردم‌شناسی ارامنه', 'گشت و گذار در سنگفرش‌های محله جلفا', 'دیدار از کاخ و کوشک باغ چهلستون', 'ترانسفر به فرودگاه و پرواز بازگشت'],
        activitiesEn: ['Vank Cathedral & Armenian history museum', 'Julfa cobblestone streets stroll', 'Chehel Sotoun Pavilion tour', 'Airport transfer and return flight'],
        meals: { breakfast: true, lunch: false, dinner: false },
        accommodation: 'پایان سفر و پرواز بازگشت',
        accommodationEn: 'End of tour & return flight',
        image: '/images/isfahan/chehel-sotoun.jpg',
      },
    ],
    reviews: [
      {
        id: 'rev-1',
        author: 'علیرضا شمس',
        rating: 5,
        date: '۱۴۰۳/۰۵/۱۸',
        comment: 'اقامت در هتل عباسی و هماهنگی راهنمای تور بی‌نقص بود. توضیحاتی که برای مسجد شیخ لطف‌الله داده شد واقعا دید ما رو نسبت به معماری ایرانی عوض کرد. حتما پیشنهاد می‌کنم.',
        commentEn: 'Staying at the Abbasi Hotel and the guide coordination was flawless. The insights into the mosque architecture changed how we appreciate Persian heritage.',
        travelType: 'سفر خانوادگی',
      },
      {
        id: 'rev-2',
        author: 'مریم کمالی',
        rating: 5,
        date: '۱۴۰۳/۰۴/۲۴',
        comment: 'کیفیت خودروهای ترانسفر و آرامش در طول برنامه عالی بود. برخورد راهنما خیلی محترمانه و حرفه‌ای بود.',
        commentEn: 'Transfer vehicle quality and relaxed tour pacing were top tier. Very polite and knowledgeable guide.',
        travelType: 'زوج',
      },
      {
        id: 'rev-3',
        author: 'پیمان نوری',
        rating: 4.5,
        date: '۱۴۰۳/۰۳/۱۱',
        comment: 'برنامه‌ریزی دقیق بود، همه ساعت‌ها به موقع اجرا شد. چایخانه هتل عباسی در عصر روز اول خاطره‌انگیزترین قسمت سفر بود.',
        commentEn: 'Punctual planning and smooth execution. The evening tea at Abbasi courtyard was our favorite memory.',
        travelType: 'سفر با دوستان',
      },
    ],
  },
  {
    id: 't2',
    title: 'تور زیارتی مشهد ویژه',
    titleEn: 'Mashhad Pilgrimage Special Luxury Tour',
    city: 'مشهد',
    cityEn: 'Mashhad',
    country: 'ایران',
    countryEn: 'Iran',
    durationDays: 3,
    durationNights: 2,
    price: 52000000,
    childPrice: 38000000,
    rating: 4.9,
    reviewsCount: 286,
    imageQuery: 'imam-reza-shrine',
    category: 'cultural',
    heroImage: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&q=80&w=1600',
    gallery: [
      'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&q=80&w=1200',
      'https://www.eghamat24.com/app/public/hotel_images/original/Mashhad-Darvishi-44.jpg',
      'https://www.eghamat24.com/app/public/hotel_images/original/Mashhad-Darvishi-90.jpg',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&q=80&w=1200',
    ],
    summary: 'تجربه معنوی و آرامش‌بخش در پایتخت معنوی ایران با اقامت در هتل ۵ ستاره مجلل درویشی نزدیک به حرم مطهر و خدمات فول‌بُرد.',
    summaryEn: 'A serene and spiritual journey to Mashhad, staying at the luxurious 5-star Darvishi Royal Hotel steps away from the Holy Shrine with full-board gourmet meals.',
    description: 'تور زیارتی مشهد مقدس فیروزو برای مسافرانی طراحی شده است که در کنار آرامش زیارت، خواهان آسودگی خاطر و امکانات هتل‌های مجلل هستند. با پرواز اختصاصی به مشهد سفر کنید، در هتل مجلل درویشی با منوی بوفه کامل صبحانه، ناهار و شام اقامت داشته باشید و از ترانسفر رفت و برگشت فرودگاهی رایگان بهره‌مند شوید.',
    descriptionEn: 'Designed for pilgrims seeking tranquility and elevated comfort. Enjoy return flights, 5-star full-board dining at Darvishi Royal Hotel, roundtrip VIP airport transfers, and guided tours of Khorasan historical gems including Ferdowsi Mausoleum in Tus.',
    highlights: [
      'اقامت در هتل ۵ ستاره درویشی (فاصله پیاده کمتر از ۵ دقیقه تا حرم)',
      'پکیج فول‌بُرد شامل صبحانه، ناهار و شام بوفه مجلل',
      'استقبال VIP فرودگاهی با تشریفات اختصاصی',
      'گشت نیم‌روزی شاندیز و صرف شیشلیک اصیل خراسانی',
      'بازدید از آرامگاه حکیم ابوالقاسم فردوسی در شهر تاریخی توس',
      'خرید بهترین زعفران صادراتی قائنات و زرشک درجه یک با تضمین اصالت',
    ],
    highlightsEn: [
      'Stay at prestigious 5-star Darvishi Royal Hotel near the Shrine',
      'Full-board package (Buffet Breakfast, Lunch & Dinner included)',
      'Complimentary airport CIP welcome and transfers',
      'Excursion to scenic Shandiz with authentic Shishlik dining',
      'Visit to the grand Ferdowsi Tomb in historic Tus',
      'Curated saffron and barberry shopping with certified quality',
    ],
    includes: [
      'بلیط پرواز رفت و برگشت با ایرلاین معتبر',
      '۲ شب اقامت در هتل ۵ ستاره درویشی با کلیه وعده‌های غذایی (فول‌بُرد)',
      'ترانسفر اختصاصی فرودگاه به هتل و بالعکس',
      'گشت توس، آرامگاه فردوسی و ییلاقات شاندیز',
      'بیمه مسافرتی کامل',
    ],
    excludes: [
      'خدمات مینی‌بار و روم‌سرویس هتل',
      'خریدهای شخصی و سوغات',
    ],
    hotelName: 'هتل مجلل ۵ ستاره درویشی مشهد',
    hotelStars: 5,
    transportType: 'پرواز رفت و برگشت + ترانسفر اختصاصی ون هیوندای',
    transportTypeEn: 'Return flights + Private Hyundai Staria van transfers',
    groupSize: 'تور خانوادگی و اختصاصی',
    groupSizeEn: 'Private & family tour',
    guideLanguages: ['فارسی', 'العربية', 'English'],
    cancellationPolicy: {
      freeUntilDays: 5,
      description: 'کنسلی تا ۵ روز قبل از پرواز رایگان است. از ۵ تا ۲ روز پیش از سفر کسر هزینه یک شب هتل و از ۴۸ ساعت مانده به پرواز بدون استرداد خواهد بود.',
      descriptionEn: 'Free cancellation up to 5 days before trip. Within 5-2 days one night fee applies. Non-refundable under 48 hours.',
    },
    departureDates: [
      {
        id: 'd1-t2',
        startDate: daysFromNow(3),
        endDate: daysFromNow(6),
        price: 52000000,
        childPrice: 38000000,
        availableSeats: 5,
        guaranteed: true,
      },
      {
        id: 'd2-t2',
        startDate: daysFromNow(10),
        endDate: daysFromNow(13),
        price: 52000000,
        childPrice: 38000000,
        availableSeats: 8,
        guaranteed: true,
      },
      {
        id: 'd3-t2',
        startDate: daysFromNow(17),
        endDate: daysFromNow(20),
        price: 54000000,
        childPrice: 39000000,
        availableSeats: 10,
        guaranteed: true,
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'پرواز به مشهد، تشریفات فرودگاهی و زیارت اول',
        titleEn: 'Flight to Mashhad, VIP pickup & First Pilgrimage',
        description: 'ورود به فرودگاه مشهد، ترانسفر تشریفاتی با ون اختصاصی به هتل درویشی و تحویل اتاق‌ها. عصرگاه زیارت اول در صحن‌های مطهر و اقامه نماز، همراه با ضیافت شام بوفه هتل.',
        descriptionEn: 'Arrival at Mashhad, private VIP van transfer to Darvishi Hotel, followed by check-in. Evening pilgrimage to the Holy Shrine and dinner buffet.',
        activities: ['استقبال VIP فرودگاه مشهد', 'پذیرش و اقامت در هتل درویشی', 'زیارت اول و طواف در صحن‌های حرم مطهر', 'شام بوفه در رستوران مجلل هتل'],
        activitiesEn: ['VIP airport greeting', 'Hotel check-in at Darvishi', 'First evening shrine pilgrimage', 'Buffet dinner at hotel restaurant'],
        meals: { breakfast: false, lunch: false, dinner: true },
        accommodation: 'هتل ۵ ستاره درویشی مشهد',
        accommodationEn: '5-star Darvishi Royal Hotel',
        image: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&q=80&w=800',
      },
      {
        day: 2,
        title: 'زیارت سحرگاهی، گشت توس و ناهار در شاندیز',
        titleEn: 'Dawn Prayers, Tus Excursion & Shandiz Lunch',
        description: 'صبح زود زمزمه دعای سحر در حرم مطهر. بعد از صبحانه، حرکت به سوی شهر کهن توس برای دیدار با مزار حماسه‌سرای بزرگ پارسی، فردوسی پاکزاد. ظهر ناهار را در باغ‌رستوران شاندیز صرف می‌کنیم.',
        descriptionEn: 'Morning spiritual time. After breakfast, journey to Tus to honor legendary poet Ferdowsi. Enjoy authentic lunch in scenic mountain gardens of Shandiz.',
        activities: ['حضور سحرگاهی در رواق‌های حرم', 'گشت آرامگاه فردوسی و کهن‌دژ توس', 'صرف شیشلیک مخصوص در شاندیز', 'عصرانه و گشت بازار رضا برای سوغات'],
        activitiesEn: ['Dawn prayers at shrine', 'Ferdowsi mausoleum visit', 'Traditional Shandiz shishlik lunch', 'Bazaar Reza shopping tour'],
        meals: { breakfast: true, lunch: true, dinner: true },
        accommodation: 'هتل ۵ ستاره درویشی مشهد',
        accommodationEn: '5-star Darvishi Royal Hotel',
        image: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&q=80&w=800',
      },
      {
        day: 3,
        title: 'زیارت وداع، خرید زعفران و بازگشت',
        titleEn: 'Farewell Pilgrimage, Saffron Shopping & Departure',
        description: 'آخرین زیارت و عرض ارادت، تسویه حساب هتل، خرید زعفران و نبات درجه یک با هماهنگی تور لیدر و ترانسفر به فرودگاه مشهد جهت پرواز بازگشت.',
        descriptionEn: 'Final farewell prayer at the Shrine, checkout, certified saffron tasting and shopping, and private transfer back to the airport for return flight.',
        activities: ['زیارت وداع با حرم امام رضا (ع)', 'خرید زعفران اصیل قائنات با تضمین آزمایشگاهی', 'ترانسفر به فرودگاه بین‌المللی مشهد'],
        activitiesEn: ['Farewell prayers', 'Premium saffron shopping', 'Airport departure transfer'],
        meals: { breakfast: true, lunch: false, dinner: false },
        accommodation: 'پایان سفر',
        accommodationEn: 'End of tour',
        image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&q=80&w=800',
      },
    ],
    reviews: [
      {
        id: 'rev-4',
        author: 'زهرا موسوی',
        rating: 5,
        date: '۱۴۰۳/۰۶/۰۲',
        comment: 'غذاهای بوفه هتل درویشی واقعا درجه یک بود و نزدیکی به حرم برای مادر سالمندم بی‌اندازه راحت و عالی بود. از فیروزو بابت هماهنگی خوب سپاسگزارم.',
        commentEn: 'Buffet dining at Darvishi was marvelous and the short walk to the shrine made it effortless for my elderly mother.',
        travelType: 'سفر خانوادگی',
      },
      {
        id: 'rev-5',
        author: 'حسین صادقی',
        rating: 4.8,
        date: '۱۴۰۳/۰۵/۲۷',
        comment: 'همه چیز بسیار منظم، پرواز بدون تاخیر و ماشین ترانسفر بسیار تمیز بود.',
        commentEn: 'Everything was remarkably well organized, punctual flights, clean transfer van.',
        travelType: 'سفر تک‌نفره',
      },
    ],
  },
  {
    id: 't3',
    title: 'تور درمانی استانبول + چکاپ کامل',
    titleEn: 'Istanbul Medical Checkup & Wellness Tour',
    city: 'استانبول',
    cityEn: 'Istanbul',
    country: 'ترکیه',
    countryEn: 'Turkey',
    durationDays: 5,
    durationNights: 4,
    price: 185000000,
    childPrice: 130000000,
    rating: 4.7,
    reviewsCount: 95,
    imageQuery: 'istanbul-medical',
    category: 'medical',
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=1600',
    gallery: [
      'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=1200',
    ],
    summary: 'ترکیبی از بالاترین استانداردهای پزشکی بین‌المللی (JCI) در بیمارستان‌های تراز اول استانبول به همراه اقامت لوکس ۵ ستاره و گشت‌های رویایی بسفر.',
    summaryEn: 'Comprehensive JCI-accredited executive medical checkup and wellness journey in Istanbul combined with 5-star hospitality and private Bosphorus yacht cruise.',
    description: 'این پکیج پیشرفته شامل چکاپ فوق‌تخصصی VIP در معتبرترین بیمارستان بین‌المللی استانبول (Acıbadem / Memorial)، همراهی مترجم پزشکی فارسی‌زبان در کلیه مراحل آزمایشات و معاینات، اقامت در هتل ۵ ستاره در شیشلی، و گشت‌های آرامش‌بخش دریایی و شهری در استانبول است.',
    descriptionEn: 'An elite healthcare and wellness package featuring full executive checkup at JCI-accredited Istanbul hospitals (Acibadem/Memorial), a dedicated medical interpreter throughout tests and consultations, 5-star hotel in Sisli, VIP private transfers, and a scenic Bosphorus yacht cruise.',
    highlights: [
      'پکیج کامل چکاپ جامع سلامت با بیش از ۶۰ پارامتر آزمایشگاهی و تصویربرداری MRI/سی‌تی‌اسکن',
      'معاینه توسط اساتید متخصص قلب، داخلی، چشم و مغز و اعصاب',
      'مترجم همراه پزشکی مسلط به اصطلاحات تخصصی ترکی و انگلیسی',
      'اقامت ۴ شب در هتل ۵ ستاره Radisson Blu یا Hilton شیشلی',
      'ترانسفر فرودگاهی و بیمارستانی رفت و برگشت با مرسدس بنز VIP',
      'کروز اختصاصی غروب آفتاب در تنگه بسفر و تماشای کاخ دلمه‌باغچه',
      'فرصت خرید از مراکز لوکس زورلو سنتر و جواهیر',
    ],
    highlightsEn: [
      'Comprehensive executive checkup covering 60+ biomarkers, MRI and cardiology workups',
      'Specialist consultations across Cardiology, Oncology, Neurology & Internal medicine',
      'Personal medical interpreter accompanying every appointment',
      '4 nights in 5-star Radisson Blu or Hilton Sisli Istanbul',
      'Mercedes VIP hospital and airport private transfers',
      'Private sunset yacht cruise along the Bosphorus Strait',
      'Leisure shopping time at Zorlu Center & Cevahir Mall',
    ],
    includes: [
      'بلیط پرواز رفت و برگشت ترکیش ایرلاینز / ماهان',
      '۴ شب اقامت در هتل ۵ ستاره با صبحانه بوفه',
      'پکیج جامع چکاپ بیمارستانی تایید شده با گزارش رسمی انگلیسی',
      'مترجم همزمان پزشکی اختصاصی در تمام جلسات درمانی',
      'ترانسفر اختصاصی فرودگاهی و کلینیکی',
      'کروز اختصاصی در تنگه بسفر',
      'بیمه مسافرتی بین‌المللی با پوشش درمانی',
    ],
    excludes: [
      'هزینه اقدامات درمانی جراحی یا دارویی اضافه بر چکاپ پایه',
      'وعده‌های ناهار و شام شخصی',
      'عوارض خروج از کشور',
    ],
    hotelName: 'هتل ۵ ستاره رادیسون بلو شیشلی استانبول',
    hotelStars: 5,
    transportType: 'پرواز رفت و برگشت + ترانسفر VIP مرسدس بنز',
    transportTypeEn: 'Return flights + Mercedes-Benz VIP van',
    groupSize: 'تور کاملاً خصوصی و سفارشی (۱ تا ۴ نفر)',
    groupSizeEn: 'Private custom tour (1 to 4 travelers)',
    guideLanguages: ['فارسی', 'Türkçe', 'English'],
    cancellationPolicy: {
      freeUntilDays: 10,
      description: 'امکان کنسلی رایگان تا ۱۰ روز قبل از سفر. به دلیل رزرو بیمارستانی، از ۱۰ تا ۴ روز کسر ۲۰٪ هزینه هتل و کمتر از ۴ روز با کسر ۵۰٪ انجام می‌شود.',
      descriptionEn: 'Free cancellation up to 10 days before departure. Hospital reservation slots incur 20% penalty between 10-4 days, 50% under 4 days.',
    },
    departureDates: [
      {
        id: 'd1-t3',
        startDate: daysFromNow(7),
        endDate: daysFromNow(12),
        price: 185000000,
        childPrice: 130000000,
        availableSeats: 4,
        guaranteed: true,
      },
      {
        id: 'd2-t3',
        startDate: daysFromNow(14),
        endDate: daysFromNow(19),
        price: 185000000,
        childPrice: 130000000,
        availableSeats: 6,
        guaranteed: true,
      },
      {
        id: 'd3-t3',
        startDate: daysFromNow(21),
        endDate: daysFromNow(26),
        price: 190000000,
        childPrice: 135000000,
        availableSeats: 4,
        guaranteed: true,
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'ورود به استانبول، ترانسفر VIP و پذیرش هتل',
        titleEn: 'Arrival in Istanbul, VIP transfer & Hotel Check-in',
        description: 'فرود در فرودگاه استانبول (IST)، استقبال اختصاصی و ترانسفر به هتل ۵ ستاره در شیشلی. جلسه مشاوره اولیه با هماهنگ‌کننده پزشکی و بررسی پرونده سلامت.',
        descriptionEn: 'Landing at Istanbul Airport (IST), private Mercedes transfer to Sisli 5-star hotel. Evening briefing with medical coordinator to review schedule.',
        activities: ['استقبال فرودگاهی و ترانسفر به شیشلی', 'تحویل اتاق و استراحت', 'جلسه هماهنگی با مترجم پزشکی'],
        activitiesEn: ['Airport VIP reception', 'Hotel check-in and rest', 'Medical itinerary review with coordinator'],
        meals: { breakfast: false, lunch: false, dinner: true },
        accommodation: 'هتل ۵ ستاره رادیسون بلو شیشلی',
        accommodationEn: '5-star Radisson Blu Sisli Hotel',
        image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&q=80&w=800',
      },
      {
        day: 2,
        title: 'روز چکاپ بیمارستانی و تصویربرداری تشخیصی',
        titleEn: 'Hospital Checkup & Diagnostic Imaging Day',
        description: 'صبح ناشتا حرکت به بیمارستان بین‌المللی همراه مترجم اختصاصی. انجام آزمایش‌های کامل خون، سونوگرافی کامل، اکوکاردیوگرافی، تست ورزش و اسکن‌ها.',
        descriptionEn: 'Morning transfer to international hospital. Executive diagnostic protocol including blood panels, ultrasound, echocardiogram, and physician exams.',
        activities: ['انتقال اختصاصی به بیمارستان مموریال یا آجی‌بادم', 'آزمایشات جامع و تصویربرداری با همراهی مترجم', 'صرف صبحانه سالم بیمارستان پس از آزمایش خون', 'معاینه اساتید متخصص و بازگشت به هتل'],
        activitiesEn: ['Private transfer to hospital', 'Comprehensive diagnostic suite with translator', 'Post-test healthy breakfast', 'Specialist consultations & hotel return'],
        meals: { breakfast: true, lunch: true, dinner: false },
        accommodation: 'هتل ۵ ستاره رادیسون بلو شیشلی',
        accommodationEn: '5-star Radisson Blu Sisli Hotel',
        image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=800',
      },
      {
        day: 3,
        title: 'نتایج پزشکی، مشاوره نهایی و گشت کروز بسفر',
        titleEn: 'Medical Results, Doctor Consultation & Yacht Cruise',
        description: 'جلسه تحلیل گزارش نهایی با پزشک ارشد و دریافت نسخه و برنامه تغذیه. عصرگاه به عنوان پاداش سلامتی، گشت اختصاصی با یات روی تنگه بسفر خواهیم داشت.',
        descriptionEn: 'Review of comprehensive health dossier with lead doctor. Translated official reports in English. Afternoon private yacht cruise over Bosphorus.',
        activities: ['جلسه تحلیل نتایج چکاپ با حضور مترجم', 'دریافت گزارش تفصیلی سلامت به زبان انگلیسی', 'کروز اختصاصی یات بر روی آب‌های نیلگون بسفر', 'شام در رستوران رو به دریا'],
        activitiesEn: ['Final medical review session', 'English certified health report handover', 'Private Bosphorus sunset yacht cruise', 'Seaside dinner'],
        meals: { breakfast: true, lunch: false, dinner: true },
        accommodation: 'هتل ۵ ستاره رادیسون بلو شیشلی',
        accommodationEn: '5-star Radisson Blu Sisli Hotel',
        image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=800',
      },
      {
        day: 4,
        title: 'روز تفریح و خرید در استانبول مدرن و سنتی',
        titleEn: 'Leisure, Shopping & Historic Highlights',
        description: 'روز آزاد با همراهی لیدر محلی برای بازدید از مرکز خرید لوکس زورلو یا بازار بزرگ استانبول و تجربه حمام سنتی ترکی جهت رفع کامل خستگی.',
        descriptionEn: 'Free leisure day with local guide options for luxury shopping at Zorlu Center, Grand Bazaar, or relaxing in a historic Ottoman Turkish bath.',
        activities: ['خرید در مراکز تجاری برتر استانبول', 'تجربه حمام سنتی ترکی و اسپا (اختیاری)', 'کافه‌گردی در اورتاکوی و طعم وافل و کمپیر'],
        activitiesEn: ['Shopping in premier malls', 'Optional historic hammam and spa', 'Ortakoy waterfront stroll'],
        meals: { breakfast: true, lunch: false, dinner: false },
        accommodation: 'هتل ۵ ستاره رادیسون بلو شیشلی',
        accommodationEn: '5-star Radisson Blu Sisli Hotel',
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800',
      },
      {
        day: 5,
        title: 'تسویه حساب و ترانسفر به فرودگاه استانبول',
        titleEn: 'Checkout & Private Airport Transfer',
        description: 'صرف آخرین صبحانه لذیذ بوفه، تحویل اتاق و ترانسفر تشریفاتی به فرودگاه استانبول برای پرواز بازگشت به کشور.',
        descriptionEn: 'Enjoy the final gourmet breakfast, checkout, and luxury transfer to Istanbul Airport for return flight home.',
        activities: ['تسویه حساب و تحویل بار', 'ترانسفر فرودگاهی و پرواز بازگشت'],
        activitiesEn: ['Hotel checkout', 'Airport transfer and departure'],
        meals: { breakfast: true, lunch: false, dinner: false },
        accommodation: 'پایان تور',
        accommodationEn: 'End of tour',
        image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=80&w=800',
      },
    ],
    reviews: [
      {
        id: 'rev-6',
        author: 'دکتر محمدرضا جلالی',
        rating: 5,
        date: '۱۴۰۳/۰۴/۱۵',
        comment: 'سطح بیمارستان و دستگاه‌های تشخیصی در حد بالاترین مراکز اروپایی بود. حضور مترجم تخصصی در تمام ساعات کارم رو خیلی راحت کرد. از تیم فیروزو متشکرم.',
        commentEn: 'Hospital infrastructure and diagnostic gear rival the best in Europe. The dedicated medical interpreter made every step effortless.',
        travelType: 'سفر انفرادی سلامت',
      },
      {
        id: 'rev-7',
        author: 'فرشته امینی',
        rating: 4.6,
        date: '۱۴۰۳/۰۳/۲۲',
        comment: 'ترکیب درمان و گردش در این سفر فوق‌العاده بود. هتل عالی بود و برنامه بسفر بسیار خاطره‌انگیز شد.',
        commentEn: 'Blending wellness with vacation was wonderful. The hotel was top notch and the cruise was lovely.',
        travelType: 'سفر با همسر',
      },
    ],
  },
  {
    id: 't4',
    title: 'تور ماجراجویی گرجستان',
    titleEn: 'Georgia Mountain & Nature Adventure Tour',
    city: 'تفلیس و قازبگی',
    cityEn: 'Tbilisi & Kazbegi',
    country: 'گرجستان',
    countryEn: 'Georgia',
    durationDays: 6,
    durationNights: 5,
    price: 142000000,
    childPrice: 98000000,
    rating: 4.6,
    reviewsCount: 78,
    imageQuery: 'georgia-mountains',
    category: 'adventure',
    heroImage: 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&q=80&w=1600',
    gallery: [
      'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&q=80&w=1200',
    ],
    summary: 'هیجان فتح ارتفاعات قفقاز، صعود آفرود به کلیسای گرگتی، رفتینگ در رودخانه‌های خروشان و اقامت در هتل‌های کوهستانی لوکس گرجستان.',
    summaryEn: 'Thrilling Caucasus mountain expedition featuring Kazbegi 4x4 off-road ascent, Aragvi river white-water rafting, and stay at iconic Rooms Hotel Kazbegi.',
    description: 'گرجستان سرزمین کوه‌های مه‌آلود، دره‌های سرسبز و قلعه‌های باستانی است. در این تور مهیج ۶ روزه، از کوچه‌های سنگفرش تفلیس قدیم آغاز کرده، در امتداد جاده نظامی گرجستان به سمت قله قازبگی پیش می‌رویم و تجربه‌هایی بی‌نظیر از رفتینگ، پاراگلایدر، آفرود و کمپ‌های کوهستانی را رقم می‌زنیم.',
    descriptionEn: 'Experience the rugged alpine beauty of Georgia. Explore cobblestone streets of Old Tbilisi, drive the historic Georgian Military Highway, take 4x4 vehicles up to Gergeti Trinity Church below Mount Kazbek, and enjoy white-water rafting on the roaring Aragvi.',
    highlights: [
      'اقامت در هتل مشهور Rooms Hotel Kazbegi با چشم‌انداز خیره‌کننده کوه قازبک',
      'صعود آفرود ۴×۴ به کلیسای تاریخی ترینیتی گرگتی در ارتفاع ۲۱۷۰ متری',
      'رفتینگ مهیج در آب‌های خروشان رودخانه آراگوی با مربیان بین‌المللی',
      'بازدید از قلعه تاریخی آنانوری و دریاچه فیروزه‌ای ژینوالی',
      'گشت پیاده‌روی در شهر قدیم تفلیس، پل صلح و تله‌کابین ناریکالا',
      'چشیدن خینکالی، خاچاپوری و ضیافت سنتی گرجی (سوپرا)',
    ],
    highlightsEn: [
      'Stay at the world-renowned Rooms Hotel Kazbegi facing Mount Kazbek',
      '4x4 off-road drive up to Gergeti Trinity Church at 2,170m altitude',
      'White-water rafting adventure on Aragvi river with certified river guides',
      'Ananuri Fortress visit overlooking turquoise Jinvali water reservoir',
      'Old Tbilisi walking tour, Peace Bridge, and Narikala cable car',
      'Authentic Georgian supra feast tasting Khachapuri and Khinkali',
    ],
    includes: [
      'بلیط پرواز رفت و برگشت به تفلیس',
      '۳ شب اقامت در تفلیس + ۲ شب اقامت در هتل کوهستانی قازبگی با صبحانه',
      'کلیه ترانسفرهای بین‌شهری و آفرود با خودروهای مجهز ۴×۴',
      'بسته کامل ماجراجویی (تجهیزات رفتینگ، جلیقه و کلاه ایمنی)',
      'راهنمای تخصصی کوهنوردی و طبیعت‌گردی',
      'بیمه حوادث ورزشی و مسافرتی ویژه',
    ],
    excludes: [
      'پرواز با پاراگلایدر در گودائوری (اختیاری با هزینه جداگانه)',
      'ناهار و شام‌های شخصی خارج از برنامه سوپرا',
      'تجهیزات و البسه شخصی کوهنوردی',
    ],
    hotelName: 'هتل ۵ ستاره رومز قازبگی + هتل رادیسون تفلیس',
    hotelStars: 5,
    transportType: 'پرواز + خودروهای آفرود لندکروزر و ون توریستی',
    transportTypeEn: 'Flights + 4x4 Land Cruisers & tourist Mercedes Sprinter',
    groupSize: 'حداکثر ۱۶ نفر',
    groupSizeEn: 'Max 16 adventurers',
    guideLanguages: ['فارسی', 'English', 'ქართული'],
    cancellationPolicy: {
      freeUntilDays: 8,
      description: 'کنسلی تا ۸ روز پیش از شروع تور بدون جریمه انجام می‌شود. کمتر از ۸ روز به علت رزرو خودروهای آفرود و هتل کوهستانی، مشمول ۴۰٪ جریمه خواهد بود.',
      descriptionEn: 'Free cancellation up to 8 days before departure. Under 8 days subject to 40% penalty due to mountain lodge and 4x4 booking.',
    },
    departureDates: [
      {
        id: 'd1-t4',
        startDate: daysFromNow(6),
        endDate: daysFromNow(12),
        price: 142000000,
        childPrice: 98000000,
        availableSeats: 7,
        guaranteed: true,
      },
      {
        id: 'd2-t4',
        startDate: daysFromNow(15),
        endDate: daysFromNow(21),
        price: 142000000,
        childPrice: 98000000,
        availableSeats: 10,
        guaranteed: true,
      },
      {
        id: 'd3-t4',
        startDate: daysFromNow(24),
        endDate: daysFromNow(30),
        price: 146000000,
        childPrice: 102000000,
        availableSeats: 6,
        guaranteed: true,
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'ورود به تفلیس و گشت شبانه شهر قدیم',
        titleEn: 'Arrival in Tbilisi & Old Town Evening Walk',
        description: 'پرواز به تفلیس، استقبال فرودگاهی و تحویل هتل. غروب را با قدم زدن در محله حمام‌های گوگردی آبانتوبانی و سوار شدن به تله‌کابین قلعه ناریکالا سپری می‌کنیم.',
        descriptionEn: 'Arrival at Tbilisi airport, transfer to hotel. Evening stroll in Abanotubani sulfur bath district and cable car ride up to Narikala fortress.',
        activities: ['ترانسفر از فرودگاه تفلیس به هتل', 'تله‌کابین قلعه ناریکالا و چشم‌انداز ۳۶۰ درجه شهر', 'شام خوشامدگویی خاچاپوری در رستوران سنتی'],
        activitiesEn: ['Airport transfer to central hotel', 'Narikala cable car panoramic ride', 'Welcome dinner featuring Georgian Khachapuri'],
        meals: { breakfast: false, lunch: false, dinner: true },
        accommodation: 'هتل ۴ ستاره رادیسون رد تفلیس',
        accommodationEn: '4-star Radisson RED Tbilisi',
        image: 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?auto=format&fit=crop&q=80&w=800',
      },
      {
        day: 2,
        title: 'جاده نظامی گرجستان، قلعه آنانوری و ورود به قازبگی',
        titleEn: 'Georgian Military Road, Ananuri Fortress & Kazbegi',
        description: 'حرکت در یکی از زیباترین جاده‌های کوهستانی جهان؛ توقف در سد ژینوالی و قلعه قرون وسطایی آنانوری. گذر از پیست اسکی گودائوری و بنای یادبود دوستی ملل و اقامت در هتل رومز قازبگی.',
        descriptionEn: 'Scenic drive north on the Georgian Military Highway. Stops at Jinvali lake, Ananuri Fortress, and Gudauri viewpoint monument before reaching Stepantsminda.',
        activities: ['توقف عکاسی در سد فیروزه‌ای ژینوالی', 'بازدید از برج‌ها و دیوارهای قلعه آنانوری', 'ورود به هتل نمادین Rooms Kazbegi و تماشای قله مه‌آلود قازبک'],
        activitiesEn: ['Scenic photography at Jinvali reservoir', 'Ananuri Fortress exploration', 'Check-in to iconic Rooms Hotel Kazbegi with mountain vistas'],
        meals: { breakfast: true, lunch: true, dinner: false },
        accommodation: 'هتل ۵ ستاره رومز قازبگی',
        accommodationEn: '5-star Rooms Hotel Kazbegi',
        image: 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&q=80&w=800',
      },
      {
        day: 3,
        title: 'آفرود هیجان‌انگیز به کلیسای گرگتی و دره داریکالی',
        titleEn: 'Off-road to Gergeti Trinity & Dariali Gorge',
        description: 'سوار بر لندکروزر ۴×۴ از مسیرهای پرپیچ‌وخم کوهستانی به ارتفاع ۲۱۷۰ متری صعود می‌کنیم تا به کلیسای سنگی گرگتی در پای قله ۵۰۴۷ متری قازبک برسیم. بعدازظهر گشت دره صخره‌ای داریکالی.',
        descriptionEn: 'Embark on rugged 4x4 vehicles winding up to 2,170 meters where Gergeti Trinity Church stands against Mount Kazbek. Afternoon drive through dramatic Dariali Gorge.',
        activities: ['آفرود لندکروزر تا کلیسای ترینیتی گرگتی', 'پیاده‌روی سبک و عکاسی کوهستانی', 'بازدید از مرز گرجستان و صخره‌های داریکالی'],
        activitiesEn: ['4x4 Land Cruiser safari to Gergeti', 'Alpine photography walk', 'Dariali Gorge canyon excursion'],
        meals: { breakfast: true, lunch: false, dinner: true },
        accommodation: 'هتل ۵ ستاره رومز قازبگی',
        accommodationEn: '5-star Rooms Hotel Kazbegi',
        image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&q=80&w=800',
      },
      {
        day: 4,
        title: 'ماجراجویی رفتینگ در رودخانه آراگوی و بازگشت به تفلیس',
        titleEn: 'White-Water Rafting on Aragvi & Return to Tbilisi',
        description: 'تجربه هیجان‌انگیز قایق‌سواری در آب‌های خروشان رودخانه آراگوی با راهنمایان نجات غریق بین‌المللی. پس از صرف ناهار کبابی در کنار رودخانه، به تفلیس بازمی‌گردیم.',
        descriptionEn: 'Exciting 12 km white-water rafting trip on Aragvi river with safety briefings and certified gear. Riverside barbecue lunch before driving back to Tbilisi.',
        activities: ['آموزش و شروع رفتینگ ۱۲ کیلومتری آراگوی', 'ناهار باربیکیو گرجی در ساحل رودخانه', 'بازگشت به هتل در تفلیس و استراحت'],
        activitiesEn: ['12km white-water rafting on Aragvi', 'Riverside Georgian BBQ lunch', 'Transfer back to Tbilisi hotel'],
        meals: { breakfast: true, lunch: true, dinner: false },
        accommodation: 'هتل ۴ ستاره رادیسون رد تفلیس',
        accommodationEn: '4-star Radisson RED Tbilisi',
        image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&q=80&w=800',
      },
      {
        day: 5,
        title: 'تفلیس مدرن، مراکز خرید و ضیافت سوپرا',
        titleEn: 'Modern Tbilisi, Shopping & Festive Supra Night',
        description: 'گشت خیابان روستاولی، موزه ملی و زمان آزاد برای خرید در تفلیس مال. شب پایانی را با ضیافت شام باشکوه گرجی (سوپرا) همراه با موسیقی زنده فولکلور جشن می‌گیریم.',
        descriptionEn: 'Rustaveli Avenue exploration, shopping leisure at Tbilisi Mall, followed by a celebratory farewell Georgian Supra feast with polyphonic folklore music.',
        activities: ['قدم‌زنی در بلوار روستاولی و میدان آزادی', 'خرید صنایع دستی و سوغاتی چورچخلا', 'جشن شام سنتی سوپرا با اجرای موسیقی و رقص گرجی'],
        activitiesEn: ['Rustaveli Avenue stroll', 'Churchkhela sweets & handicraft shopping', 'Traditional Supra farewell feast with live dance'],
        meals: { breakfast: true, lunch: false, dinner: true },
        accommodation: 'هتل ۴ ستاره رادیسون رد تفلیس',
        accommodationEn: '4-star Radisson RED Tbilisi',
        image: 'https://images.unsplash.com/photo-1565008447742-97f6f38c985c?auto=format&fit=crop&q=80&w=800',
      },
      {
        day: 6,
        title: 'بدرقه و پرواز بازگشت',
        titleEn: 'Departure & Flight Home',
        description: 'صرف صبحانه، تحویل اتاق‌ها و ترانسفر به فرودگاه بین‌المللی تفلیس با خاطرات فراموش‌نشدنی از کوهستان‌های قفقاز.',
        descriptionEn: 'Breakfast, check-out, and transfer to Tbilisi International Airport for your return flight home.',
        activities: ['صرف صبحانه و تسویه هتل', 'ترانسفر به فرودگاه تفلیس و پرواز'],
        activitiesEn: ['Breakfast and check-out', 'Transfer to Tbilisi Airport'],
        meals: { breakfast: true, lunch: false, dinner: false },
        accommodation: 'پایان سفر',
        accommodationEn: 'End of tour',
        image: 'https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&q=80&w=800',
      },
    ],
    reviews: [
      {
        id: 'rev-8',
        author: 'آرمان فیاض',
        rating: 5,
        date: '۱۴۰۳/۰۴/۰۹',
        comment: 'اقامت در هتل رومز قازبگی و منظره قله صبح زود یکی از بهترین لحظات زندگیم بود! آفرود و رفتینگ با لیدرهای فوق‌العاده حرفه‌ای برگزار شد.',
        commentEn: 'Waking up to the morning sunrise over Mount Kazbek at Rooms Hotel was unforgettable! Super professional rafting and off-road leaders.',
        travelType: 'سفر ماجراجویی',
      },
      {
        id: 'rev-9',
        author: 'سپیده رضوی',
        rating: 4.5,
        date: '۱۴۰۳/۰۳/۱۸',
        comment: 'برنامه پر انرژی و عالی بود. برای کسانی که عاشق طبیعت و هیجان هستند بهترین گزینه است.',
        commentEn: 'High energy and thrilling itinerary. Perfect for nature and adrenaline lovers.',
        travelType: 'سفر گروهی با دوستان',
      },
    ],
  },
  {
    id: 't5',
    title: 'تور اصفهان (۲.۵ روزه زمینی VIP)',
    titleEn: 'Isfahan 2.5-Day Overland VIP Tour',
    city: 'اصفهان',
    cityEn: 'Isfahan',
    country: 'ایران',
    countryEn: 'Iran',
    durationDays: 3,
    durationNights: 1,
    price: 9800000,
    childPrice: 6900000,
    rating: 4.9,
    reviewsCount: 48,
    imageQuery: 'isfahan-vip-tour',
    category: 'cultural',
    heroImage: '/images/isfahan/ali-qapu.jpg',
    gallery: [
      '/images/isfahan/ali-qapu.jpg',
      '/images/isfahan/khaju-bridge.jpg',
      '/images/isfahan/khaju-pavilion.jpg',
      '/images/isfahan/khaju-day.jpg',
      '/images/isfahan/sheikh-lotfollah-exterior.jpg',
      '/images/isfahan/sheikh-lotfollah.jpg',
      '/images/isfahan/chehel-sotoun.jpg',
      '/images/isfahan/menar-jonban.jpg',
      '/images/isfahan/shah-mosque.jpg',
      '/images/isfahan/jameh-mosque.jpg',
      '/images/isfahan/bazaar-handicrafts.jpg',
      '/images/isfahan/isfahan-emblem.jpg',
    ],
    summary: 'سفر ۲.۵ روزه آخر هفته به نصف جهان با اتوبوس VIP دربست، ۱ شب اقامت هتل، ۲ وعده صبحانه کامل، بازدید از میدان نقش جهان، چهلستون، محله جلفا، کلیسای وانک و شب‌نشینی پل خواجو.',
    summaryEn: 'Memorable 2.5-day weekend overland VIP tour to Isfahan featuring 1-night hotel stay, 2 breakfasts, Naqsh-e Jahan Square, Chehel Sotoun, New Julfa, and historic bridges.',
    description: 'تور خاطره‌انگیز ۲.۵ روزه اصفهان با اتوبوس VIP، سفری جذاب و اقتصادی به پایتخت هنر و تمدن صفوی است. حرکت این تور ساعت ۲۳:۵۰ چهارشنبه ۲۵ شهریور با اتوبوس ۲۵ نفره VIP دربست صندلی تخت‌شو از میدان آرژانتین تهران آغاز می‌شود. پس از ورود صبحگاهی به اصفهان و صرف اولین وعده صبحانه، گشت‌های تاریخی شامل میدان جهانی نقش جهان، مسجد شیخ لطف‌الله، کاخ عالی‌قاپو، مسجد جامع عتیق و کاخ چهلستون آغاز می‌گردد. عصر با تحویل اتاق‌های هتل و استراحت، راهی حاشیه زاینده‌رود و پل‌های تاریخی خواجو و سی‌وسه‌پل می‌شویم تا شب‌نشینی و آوازخوانی سنتی را تجربه کنیم. روز جمعه پس از صبحانه بوفه هتل، به محله سنگفرش جلفای نو و کلیسای تاریخی وانک رفته و پس از خرید گز و صنایع دستی اصیل، به سمت تهران حرکت می‌کنیم و حدود ساعت ۲۳ جمعه شب به میدان آرژانتین می‌رسیم.',
    descriptionEn: 'A classic 2.5-day weekend overland journey to Isfahan aboard a chartered VIP 25-seat recliner bus. Departing Wednesday night at 23:50 from Arjantin Square, Tehran. Highlights include UNESCO Naqsh-e Jahan Square, Sheikh Lotfollah Mosque, Ali Qapu, Chehel Sotoun Palace, Jameh Mosque, New Julfa Armenian Quarter with Vank Cathedral, and sunset stroll along Khaju and Si-o-se-pol bridges. Returns to Tehran on Friday night around 23:00.',
    highlights: [
      'میدان جهانی نقش جهان، مسجد شیخ لطف‌الله و کاخ عالی‌قاپو',
      'مسجد جامع کهن اصفهان و کاخ باشکوه چهلستون',
      'گشت شبانه و شب‌نشینی خاطره‌انگیز بر روی پل خواجو و سی‌وسه‌پل',
      'قدم‌زنی در بافت تاریخی محله جلفا و بازدید از کلیسای وانک و موزه',
      'خرید گز، پولکی و صنایع دستی اصیل از راسته‌های بازار تاریخی قیصریه',
      'درجه سختی: ۱ از ۵ (بسیار آسان، مناسب تمام رده‌های سنی و خانواده‌ها)',
      'ساعت حرکت: ۲۳:۵۰ چهارشنبه ۲۵ شهریور از میدان آرژانتین | برگشت: جمعه ۲۷ شهریور حدود ساعت ۲۳ تهران',
    ],
    highlightsEn: [
      'UNESCO-listed Naqsh-e Jahan Square, Sheikh Lotfollah Mosque & Ali Qapu',
      'Ancient UNESCO Jameh Mosque of Isfahan and Chehel Sotoun Palace',
      'Evening illuminated stroll along Khaju Bridge and Si-o-se-pol',
      'Atmospheric walking tour in New Julfa cobblestone quarter and Vank Cathedral',
      'Handicraft and authentic Gaz shopping in the historic Bazaar',
      'Difficulty Level: 1 of 5 (Easy & relaxing, suitable for all ages)',
      'Departure: 23:50 Wed Sep 16 from Arjantin Sq | Return: Fri Sep 18 ~23:00 in Tehran',
    ],
    includes: [
      'اتوبوس VIP دربست رفت و برگشت (۲۵ نفره صندلی تخت‌شو مانیتوردار)',
      'یک شب اقامت هتلی باکیفیت در مرکز شهر اصفهان',
      'دو وعده صبحانه کامل (پنجشنبه و جمعه)',
      'پذیرایی میان‌وعده در طول مسیر رفت و برگشت و گشت‌ها',
      'ورودیه تمامی اماکن تاریخی و جاذبه‌های ذکر شده در برنامه',
      'بیمه مسئولیت مدنی مسافرتی معتبر',
      'لیدر مجرب و کارت‌دار رسمی وزارت میراث فرهنگی و گردشگری',
      'مجوز رسمی برگزاری تور گردشگری',
    ],
    excludes: [
      'وعده‌های ناهار و شام (همراهی راهنما در رستوران‌های سنتی منتخب)',
      'خریدهای شخصی، سوغات و هزینه‌های خارج از برنامه مصوب',
    ],
    hotelName: 'هتل ۴ ستاره مرکز شهر اصفهان',
    hotelStars: 4,
    transportType: 'اتوبوس VIP دربست (۲۵ نفره تخت‌شو)',
    transportTypeEn: 'Chartered 25-Seat VIP Recliner Bus',
    groupSize: '۲۵ نفر (اتوبوس VIP دربست)',
    groupSizeEn: 'Max 25 people (Chartered VIP Bus)',
    guideLanguages: ['فارسی', 'English'],
    cancellationPolicy: {
      freeUntilDays: 5,
      description: 'کنسلی تا ۵ روز قبل از حرکت با کسر ۱۰٪، از ۵ تا ۲ روز پیش از حرکت با کسر ۴۰٪، و از ۴۸ ساعت مانده به سفر به دلیل هماهنگی اتوبوس و هتل بدون استرداد خواهد بود.',
      descriptionEn: 'Free cancellation up to 5 days before departure (10% fee). 40% penalty between 5 and 2 days. Non-refundable within 48 hours of departure.',
    },
    departureDates: [
      {
        id: 'd1-t5',
        startDate: '2026-09-16', // ۲۵ شهریور ۱۴۰۵
        endDate: '2026-09-18',   // ۲۷ شهریور ۱۴۰۵
        price: 9800000,
        childPrice: 6900000,
        availableSeats: 18,
        guaranteed: true,
      },
      {
        id: 'd2-t5',
        startDate: daysFromNow(15),
        endDate: daysFromNow(17),
        price: 9800000,
        childPrice: 6900000,
        availableSeats: 22,
        guaranteed: true,
      },
    ],
    itinerary: [
      {
        day: 1,
        title: 'چهارشنبه ۲۵ شهریور - حرکت شبانه از تهران به سمت اصفهان',
        titleEn: 'Wednesday Sep 16 - Night Departure from Tehran',
        description: 'تجمع همسفران ساعت ۲۳:۳۰ در میدان آرژانتین تهران، تحویل پک پذیرایی میان‌وعده، معارفه و حرکت رأس ساعت ۲۳:۵۰ با اتوبوس VIP مجهز صندلی تخت‌شو. شب‌مانی و استراحت در طول مسیر اتوبوس.',
        descriptionEn: 'Meeting at Arjantin Square Tehran at 23:30. Welcome snack pack distribution and prompt departure at 23:50 on our comfortable VIP 25-seat recliner bus. Overnight journey to Isfahan.',
        activities: [
          'تجمع در میدان آرژانتین تهران و خوشامدگویی',
          'حرکت رأس ساعت ۲۳:۵۰ با اتوبوس VIP صندلی تخت‌شو',
          'استراحت شبانه در مسیر تهران به اصفهان',
        ],
        activitiesEn: [
          'Gathering at Arjantin Square Tehran',
          '23:50 sharp departure on VIP recliner bus',
          'Comfortable overnight bus ride to Isfahan',
        ],
        meals: { breakfast: false, lunch: false, dinner: false },
        accommodation: 'اتوبوس VIP مجهز در مسیر',
        accommodationEn: 'VIP Recliner Bus in transit',
        image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=800',
      },
      {
        day: 2,
        title: 'پنجشنبه ۲۶ شهریور - نقش جهان، چهلستون، مسجد جامع و نغمه‌های پل خواجو',
        titleEn: 'Thursday Sep 17 - Naqsh-e Jahan, Chehel Sotoun & Historic Bridges',
        description: 'صبح زود رسیدن به اصفهان و صرف صبحانه پنجشنبه. آغاز گشت با میدان جهانی نقش جهان، مسجد شیخ لطف‌الله، عمارت عالی‌قاپو و راسته‌های بازار قیصریه. سپس بازدید از مسجد جامع کهن و کاخ چهلستون. عصر تحویل هتل و استراحت، و در ادامه شب‌نشینی و پیاده‌روی روی پل خواجو و سی‌وسه‌پل.',
        descriptionEn: 'Early arrival in Isfahan followed by delicious breakfast. Tour UNESCO Naqsh-e Jahan Square, Sheikh Lotfollah Mosque, Ali Qapu Palace, Grand Bazaar, historic Jameh Mosque, and Chehel Sotoun. Afternoon hotel check-in and evening walk across illuminated Khaju and Si-o-se-pol bridges.',
        activities: [
          'صرف صبحانه پنجشنبه در اصفهان',
          'گشت کامل میدان نقش جهان و عمارت عالی‌قاپو',
          'بازدید از مسجد شیخ لطف‌الله و مسجد جامع عتیق',
          'دیدار از کاخ و کوشک چهلستون',
          'تحویل اتاق‌های هتل و استراحت',
          'گشت شبانه و عکاسی روی پل خواجو و سی‌وسه‌پل با نوای آواز',
        ],
        activitiesEn: [
          'Thursday breakfast in Isfahan',
          'Complete tour of Naqsh-e Jahan Square & Ali Qapu',
          'Explore Sheikh Lotfollah and ancient Jameh Mosque',
          'Visit Chehel Sotoun Palace and Persian garden',
          'Hotel check-in and relaxation',
          'Evening stroll and music by Khaju and Si-o-se-pol bridges',
        ],
        meals: { breakfast: true, lunch: false, dinner: false },
        accommodation: 'هتل ۴ ستاره مرکز شهر اصفهان',
        accommodationEn: 'Selected 4-star hotel in Isfahan',
        image: '/images/isfahan/shah-mosque.jpg',
      },
      {
        day: 3,
        title: 'جمعه ۲۷ شهریور - محله جلفا، کلیسای وانک، خرید گز و بازگشت به تهران',
        titleEn: 'Friday Sep 18 - Armenian New Julfa, Vank Cathedral & Return',
        description: 'صرف صبحانه جمعه هتل و تسویه اتاق‌ها. حرکت به سمت محله تاریخی جلفای نو، قدم زدن در کوچه‌های سنگفرش، بازدید از کلیسای تاریخی وانک و موزه ارامنه. خرید گز اصیل اصفهان و صنایع دستی، صرف ناهار و حرکت به سوی تهران. رسیدن به تهران (میدان آرژانتین) حدود ساعت ۲۳ با کوله‌باری از خاطرات به‌یادماندنی.',
        descriptionEn: 'Hotel breakfast and check-out. Morning walk through picturesque New Julfa Armenian quarter, visiting Vank Cathedral and Museum. Shopping for authentic Gaz sweets and crafts. Return drive to Tehran, arriving at Arjantin Square around 23:00.',
        activities: [
          'صرف صبحانه جمعه هتل و تحویل اتاق‌ها',
          'قدم‌زنی در بافت تاریخی و کافه‌های محله جلفا',
          'بازدید از کلیسای تاریخی وانک و موزه ارامنه',
          'خرید گز، سوهان و پولکی اصیل اصفهان',
          'حرکت به سمت تهران و رسیدن حدود ساعت ۲۳ به میدان آرژانتین',
        ],
        activitiesEn: [
          'Friday hotel breakfast and check-out',
          'Walking tour through cobblestone Julfa alleys and cafes',
          'Visit to historic Vank Cathedral and Armenian Museum',
          'Authentic Gaz, Sohan and handicraft shopping',
          'Drive back to Tehran arriving around 23:00 at Arjantin Sq',
        ],
        meals: { breakfast: true, lunch: false, dinner: false },
        accommodation: 'پایان سفر و ورود به تهران',
        accommodationEn: 'End of tour & arrival in Tehran',
        image: '/images/isfahan/bazaar-handicrafts.jpg',
      },
    ],
    reviews: [
      {
        id: 'rev-10',
        author: 'نیلوفر راد',
        rating: 5,
        date: '۱۴۰۳/۰۶/۱۰',
        comment: 'اتوبوس VIP فوق‌العاده راحت و تمیز بود، شب حرکت عالی خوابیدیم و صبح پر انرژی گشت‌ها شروع شد. لیدر بسیار مسلط و خوش‌برخورد بود.',
        commentEn: 'The VIP bus was extremely clean and comfortable. The tour leader was knowledgeable and courteous throughout.',
        travelType: 'سفر با دوستان',
      },
      {
        id: 'rev-11',
        author: 'مهدی خسروی',
        rating: 4.8,
        date: '۱۴۰۳/۰۵/۲۶',
        comment: 'برنامه‌ریزی دقیق، همه جاذبه‌ها سر وقت دیده شد و شب‌نشینی پل خواجو فوق‌العاده لذت‌بخش بود. قیمت هم نسبت به خدمات واقعا عالیه.',
        commentEn: 'Precise scheduling, saw all attractions on time, evening Khaju bridge atmosphere was magical. Exceptional value for price.',
        travelType: 'سفر خانوادگی',
      },
      {
        id: 'rev-12',
        author: 'سارا امینی',
        rating: 5,
        date: '۱۴۰۳/۰۴/۱۵',
        comment: 'صبحانه‌ها عالی بود و هتل تمیز و دسترسی خیلی خوبی داشت. بازدید از جلفا و کلیسای وانک هم فوق‌العاده بود.',
        commentEn: 'Great breakfasts and clean hotel with superb accessibility. Visiting Julfa and Vank Cathedral was magnificent.',
        travelType: 'زوج',
      },
    ],
  },
];

export function getAllTours(): Tour[] {
  return DETAILED_TOURS;
}

export function getTourById(id: string): Tour | undefined {
  return DETAILED_TOURS.find((tour) => tour.id === id);
}

export function getRelatedTours(id: string, limit: number = 3): Tour[] {
  return DETAILED_TOURS.filter((t) => t.id !== id).slice(0, limit);
}
