apiVersion: v1
kind: ConfigMap
metadata:
  name: firuzo-config
  labels:
    app.kubernetes.io/name: firuzo-platform
    app.kubernetes.io/component: config
data:
  NODE_ENV: "production"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_TELEMETRY_DISABLED: "1"
  NEXTAUTH_URL: "https://firuzo.com"
  NEXT_PUBLIC_SITE_URL: "https://firuzo.com"
  DEMO_MODE: "false"
  NEXT_PUBLIC_DEMO_MODE: "false"
  GATEWAY_MODE: "shetab"
  REDIS_HOST: "firuzo-redis"
  REDIS_PORT: "6379"
